    <div class="container theme-showcase" role="main" style="max-width: 35%;">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Alteração de senha</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/umacoluna', array('form'=> $form, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>