 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('usuarioNovo'); ?>'" style="float: right;width:100px;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novo</button>

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('home'); ?>">Home</a></li>
      <li><a href="<?= $this->url('usuario'); ?>">Usuários</a></li>
      <li class="active">Alterar</li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Alteração de usuário</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formUsuario, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>

    <?php if($formEmpresa): ?>
      <div class="container theme-showcase" role="main">
        <div class="row">
            <div class="panel panel-danger">
              <div class="panel-heading">
                <h3 class="panel-title">Vincular empresa</h3>
              </div>
              <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formEmpresa, 'route'=> '')) ?>
                </div>
            </div>
          </div>
        </div>
      </div>


      <div class="container theme-showcase" role="main">
        <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Empresas vinculadas</h3>
            </div>
            <div class="panel-body">
              <?php if($unidades && $unidades->count() > 0): ?>
                <table class="table">
                  <tr>
                    <th style="text-align: center">Empresa</th>
                    <th style="text-align: center">Unidade</th>
                    <th style="text-align: center">Ações</th>
                </tr>
                <?php foreach($unidades as $unidade): ?>
                <tr>
                  <td style="text-align: center"><?= $unidade['nome_empresa']; ?></td>
                  <td style="text-align: center"><?= $unidade['nome_unidade']; ?></td>

                  <td style="text-align: center;">
                    <img src="<?= $this->basePath('img/deletar.png'); ?>" title="Deletar" style="cursor: pointer;" onclick="alerta('<?= $this->url('usuarioUnidadeDeletar', array('id' => $unidade['id'], 'usuario' => $usuario['id'])) ?>', 'desativar');">
                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            <?php else: ?>
              <div class="alert alert-info">Nenhuma unidade vinculada!</div>
            <?php endif; ?>
            </div>
          </div>
        </div>
      </div>
    <?php endif; ?>

    <script type="text/javascript">
      $(document).ready(function() {
        $('#cliente').attr('disabled', 'disabled');
        <?php if(!$formEmpresa): ?>
          $('#unidade').attr('disabled', 'disabled');
        <?php endif; ?>
      });
    </script>