 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('cadastrarTma'); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novo TMA</button>

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('home'); ?>">Home</a></li>
      <li><a href="<?= $this->url('listarTma'); ?>">Lista de TMA</a></li>
      <li class="active">Inserir</li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Inserir TMA</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formTma, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>


    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-danger">
          <div class="panel-heading">
              <h3 class="panel-title">Inserir ou alterar andar</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formAndar, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>






    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de andares</h3>
            </div>
            <div class="panel-body">
              <?php if($andares->count() > 0): ?>
                <table class="table">
                  <tr>
                    <th style="text-align: center">Descrição</th>
                    <th style="text-align: center">Quantidade</th>
                    <th style="text-align: center">Ações</th>
                </tr>
                <?php foreach($andares as $andar): ?>
                <tr>
                  <td style="text-align: center"><?= $andar['descricao']; ?></td>
                  <td style="text-align: center"><?= $andar['quantidade']; ?></td>
                  <td style="text-align: center;">
                    <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" 
                    onclick="location.href='<?= $this->url('alterarTma', array('id' => $tma['id'], 'andar' => $andar['id'])); ?>'" style="cursor: pointer;">
                    
                    <span style="margin-right:4px;"></span>  
                    <img src="<?= $this->basePath('img/deletar.png'); ?>" title="Deletar" style="cursor: pointer;" onclick="alerta('<?= $this->url('deletarAndarTma', array('tma' => $tma['id'], 'andar' => $andar['id'])) ?>', 'deletar');">
                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            <?php else: ?>
              <div class="alert alert-info">Nenhum TMA encontrado!</div>
            <?php endif; ?>
            </div>
          </div>
        </div>
      </div>