 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('cadastrarQmatic'); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novo qmatic</button>

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('home'); ?>">Home</a></li>
      <li><a href="<?= $this->url('listarQmatic'); ?>">Lista de qmatic</a></li>
      <li class="active"><?= $operacao ?></li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title"><?= $operacao ?> qmatic</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $form, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>

    <?php if($qmatic): ?>
    <div class="container theme-showcase" role="main">
      <img src="<?= $this->basePath($qmatic['caminho_arquivo']); ?>">
    </div>
    <?php endif; ?>