    <?php echo $this->partial('form/pesquisa', array('form'=> $formPesquisa, 'route'=> '', 'notExcel' => '')) ?>

    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
       <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('cadastrarQmatic'); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Nova qmatic</button>

      
    </div>
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de qmatic</h3>
            </div>
            <div class="panel-body">
              <?php if($qmatics->count() > 0): ?>
                <table class="table">
                  <tr>
                    <th style="text-align: center">Empresa</th>
                    <th style="text-align: center">Unidade</th>
                    <th style="text-align: center">Ações</th>
                </tr>
                <?php foreach($qmatics as $qmatic): ?>
                <tr>
                  <td style="text-align: center"><?= $qmatic['nome_empresa']; ?></td>
                  <td style="text-align: center"><?= $qmatic['nome_unidade']; ?></td>
                  <td style="text-align: center;">
                    <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" 
                    onclick="location.href='<?= $this->url('cadastrarQmatic', array('id' => $qmatic['id'])); ?>'" style="cursor: pointer;">
                    

                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            <?php else: ?>
              <div class="alert alert-info">Nenhum qmatic encontrado!</div>
            <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($qmatics,
                                        'Sliding',
                                        'view/paginator', array('route' => 'listarQmatic')); 
          ?>
        </div>
      </div>
