<div class="container theme-showcase" role="main" style="margin-bottom:10px;"> 
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Premissas</h3>
      </div>
      <div class="panel-body">
        <div class="row" style="margin-top:20px;">
              <div class="col-sm-6">
                
              <button type="button" style="width:100%;" onclick="location.href='<?= $this->url('listarFuncionario'); ?>';" class="btn btn-default">
                  <img src="<?= $this->basePath('img/people.png'); ?>" style="width:32px;height:32px;">
                  HC GERAL
              </button>
                                

              </div>

              <div class="col-sm-6">
                  <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('listarNps'); ?>'" style="width:100%;">
                  <img src="<?= $this->basePath('img/grafico.png'); ?>" alt="Salvar" style="width:32px;height:32px;">
                  NPS
                </button>
              </div>
        </div>

         <div class="row" style="margin-top:20px;">
              <div class="col-sm-6">
                
              <button type="button" style="width:100%;" onclick="location.href='<?= $this->url('listarTma'); ?>'" class="btn btn-default">
                  <img src="<?= $this->basePath('img/smiley.png'); ?>" style="width:32px;height:32px;">
                  TMA
              </button>
                                

              </div>

              <div class="col-sm-6">
                  <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('listarEvolucao'); ?>'" style="width:100%;">
                  <img src="<?= $this->basePath('img/medalha.png'); ?>" alt="Salvar" style="width:32px;height:32px;">
                  EVOLUÇÃO SIGA
                </button>
              </div>
        </div>

        <div class="row" style="margin-top:20px;">
              <div class="col-sm-6">
                
              <button type="button" style="width:100%;" onclick="location.href='<?= $this->url('listarTme'); ?>'" class="btn btn-default">
                  <img src="<?= $this->basePath('img/cronometro.png'); ?>" style="width:32px;height:32px;">
                  TME
              </button>
                                

              </div>

              <div class="col-sm-6">
                  <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('listarAvaliacoesRespondidasAdmin'); ?>'" style="width:100%;">
                  <img src="<?= $this->basePath('img/alvo.png'); ?>" alt="Salvar" style="width:32px;height:32px;">
                  AVALIAÇÃO DE DESEMPENHO
                </button>
              </div>
        </div>

        <div class="row" style="margin-top:20px;">
              <div class="col-sm-6">
                
              <button type="button" style="width:100%;" onclick="location.href='<?= $this->url('listarQmatic'); ?>'" class="btn btn-default">
                  <img src="<?= $this->basePath('img/codigoBarras.png'); ?>" style="width:32px;height:32px;">
                  QMATIC
              </button>
                                

              </div>

              <div class="col-sm-6">
                
              <button type="button" style="width:100%;" onclick="location.href='<?= $this->url('listarPremissasEquipes'); ?>'" class="btn btn-default">
                  <img src="<?= $this->basePath('img/equipes.png'); ?>" style="width:32px;height:32px;">
                  ORGANIZAÇÃO DE EQUIPES
              </button>
                                

              </div>

        </div>

        <div class="row" style="margin-top:20px;">
              <div class="col-sm-6">
                
              <button type="button" style="width:100%;" onclick="location.href='<?= $this->url('listarMira'); ?>'" class="btn btn-default">
                  <img src="<?= $this->basePath('img/download32.png'); ?>" style="width:32px;height:32px;">
                  MIRA
              </button>
                                

              </div>

        </div>



      </div>
    </div>
  </div>
</div>
   