 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('homeGestor'); ?>">Home</a></li>
      <li><a href="<?= $this->url('menuPremissas'); ?>">Menu premissas</a></li>
      <li class="active">TMA</li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">TMA - Tempo médio de atendimento</h3>
            </div>
            <div class="panel-body">
                <?php if(count($andares) == 0): ?>
                  <div class="alert alert-info">Nenhum TMA encontrado!</div>
                <?php else: ?>
                <div class="table-responsive">
                  <table class="table">
                      <tr>
                        <th style="text-align: center;color:#ffffff;background-color:#305496;" colspan="2">QUADRO NECESSÁRIO PARA MANTER O NÍVEL DE SERVIÇO</th>
                      </tr>
                      <tr>
                        <th style="text-align: center;color:#ffffff;background-color:#2f75b5;">HC LÍQUIDO</th>
                        <th style="text-align: center;color:#ffffff;background-color:#00b0f0;"><?= $andares[0]['hc_liquido'] ?></th>
                      </tr>
                      <?php foreach ($andares as $andar) : ?>
                        <tr>
                          <td style="text-align: center;color:#ffffff;background-color:#8ea9db;"><?= $andar['descricao'] ?></td>
                          <td style="text-align: center;color:#ffffff;background-color:#8ea9db;"><?= $andar['quantidade'] ?></td>
                        </tr>
                      <?php endforeach; ?>
                      <tr>
                        <th style="text-align: center;color:#ffffff;background-color:#2f75b5;">HC GERAL</th>
                        <th style="text-align: center;color:#ffffff;background-color:#00b0f0;"><?= $andares[0]['hc_geral'] ?></th>
                      </tr>
                  </table>
                </div>
                <?php endif; ?>
          </div>
      </div>
    </div>
    </div>

