 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('home'); ?>">Home</a></li>
      <li><a href="<?= $this->url('menuPremissas'); ?>">Menu premissas</a></li>
      <li class="active">TME</li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">TME - Tempo médio de espera</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <img class="img-responsive center-block" src="<?= $this->basePath($tme['caminho_imagem']); ?>">
            </div>
          </div>
      </div>
    </div>
    </div>

