 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('home'); ?>">Home</a></li>
      <li><a href="<?= $this->url('menuPremissas'); ?>">Menu premissas</a></li>
      <li class="active">MIRA</li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">MIRA</h3>
            </div>
            <div class="panel-body">
              <?php if(!$mira): ?>
                <div class="alert alert-info">Nenhum MIRA encontrado!</div>
              <?php else: ?>
                <div class="form-group">
                  <div class="row">
                    <div class="col-sm-12">
                      <h3><?= $mira['nome'].' - '.$mira['email'] ?></h3>
                    </div>
                    
                  </div>
                  <div class="row">
                    <div class="col-sm-12">
                      <img src="<?= $this->basePath($mira['imagem_1']) ?>" class="img-responsive">
                    </div>
                  </div>

                    <?php if(!empty($mira['imagem_2'])): ?>
                      <div class="row">
                        <div class="col-sm-4">
                          <img src="<?= $this->basePath($mira['imagem_2']) ?>" class="img-responsive">
                        </div>
                      </div>
                    <?php endif; ?>

                    <?php if(!empty($mira['imagem_3'])): ?>
                      <div class="row">
                        <div class="col-sm-4">
                          <img src="<?= $this->basePath($mira['imagem_3']) ?>" class="img-responsive">
                        </div>
                      </div>
                    <?php endif; ?>
                    
                  
            </div>
          <?php endif; ?>
          </div>
      </div>
    </div>
    </div>

<style type="text/css">
  .img-responsive {
    margin: 0 auto;
}
</style>