 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('home'); ?>">Home</a></li>
      <li><a href="<?= $this->url('menuPremissas'); ?>">Menu premissas</a></li>
      <li class="active"><?= $evolucao['tipo'] ?></li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title"><?= $evolucao['tipo'] ?></h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <div class="row">
                    <div class="col-sm-4" style="<?php echo $evolucao['classificacao_atual'] == 'O' ? 'border: 1px solid;' : '' ?>">
                      <?php if($evolucao['classificacao_atual'] == 'O'): ?>
                        <h3 style="text-align: center;">Classificação atual</h3>
                      <?php endif; ?>
                      <h3 style="text-align: center;">Ouro</h3>
                      <img class="img-responsive center-block" src="<?= $this->basePath('img/ouro.png'); ?>">
                    </div>
                    <div class="col-sm-4" style="<?php echo $evolucao['classificacao_atual'] == 'P' ? 'border: 1px solid;' : '' ?>">
                      <?php if($evolucao['classificacao_atual'] == 'P'): ?>
                        <h3 style="text-align: center;">Classificação atual</h3>
                      <?php endif; ?>
                      <h3 style="text-align: center;">Prata</h3>
                      <img class="img-responsive center-block" src="<?= $this->basePath('img/prata.png'); ?>">
                    </div>
                    <div class="col-sm-4" style="<?php echo $evolucao['classificacao_atual'] == 'B' ? 'border: 1px solid;' : '' ?>">
                      <?php if($evolucao['classificacao_atual'] == 'B'): ?>
                        <h3 style="text-align: center;">Classificação atual</h3>
                      <?php endif; ?>
                      <h3 style="text-align: center;">Bronze</h3>
                      <img class="img-responsive center-block" src="<?= $this->basePath('img/bronze.png'); ?>">
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-4">
                      <h4 style="text-align: center;"><?= $evolucao['ouro']; ?></h4>
                    </div>
                    <div class="col-sm-4">
                      <h4 style="text-align: center;"><?= $evolucao['prata']; ?></h4>
                    </div>
                    <div class="col-sm-4">
                      <h4 style="text-align: center;"><?= $evolucao['bronze']; ?></h4>
                    </div>
                  </div>
            </div>
          </div>
      </div>
    </div>
    </div>

