    <?php echo $this->partial('form/pesquisa', array('form'=> $formPesquisa, 'route'=> '')) ?>

    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('novoAjuda'); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Solicitar ajuda</button>

      <button type="button" class="btn btn-info disabled" style="float: right;margin-right: 10px;">
      <img src="<?php echo $this->basePath('img/recebida.png') ?>" alt="Ajudas enviadas">
      Ajudas enviadas</button>

      <button type="button" class="btn btn-success" onclick="location.href='<?= $this->url('ajudaSolicitada'); ?>'" style="float: right;margin-right: 10px;">
      <img src="<?php echo $this->basePath('img/solicitada.png') ?>" alt="Ajudas requisitadas">
      Ajudas requisitadas</button>

      <div style="float:left;">
        <span><img src="<?= $this->basePath('img/verde.png'); ?>"> Ajuda realizada</span>
        <span style="margin-left:5px;"><img src="<?= $this->basePath('img/amarelo.png'); ?>"> Realizando ajuda</span>
        <span style="margin-left:5px;"><img src="<?= $this->basePath('img/vermelho.png'); ?>"> Ajuda a realizar</span>
      </div>

    </div>
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de ajudas</h3>
            </div>
            <div class="panel-body">
              <?php if($ajudas->count() > 0): ?>
              <div class="table-responsive">
                <table class="table">
                  <tr>
                    <th style="text-align: center">Status</th>
                    <th style="text-align: center">Matrícula</th>
                    <th style="text-align: center">Funcionário</th>
                    <th style="text-align: center">Unidade de origem</th>
                    <th style="text-align: center">Área/setor de destino</th>
                    <th style="text-align: center">Início</th>
                    <th style="text-align: center">Término</th>
                    <th style="text-align: center">Horário</th>
                </tr>
                <?php foreach($ajudas as $ajuda): ?>
                <tr>
                  <?php 
                    $cor = $this->farol($this->converterData($ajuda['data_inicio']), $this->converterData($ajuda['data_fim']));
                  ?>
                  <td style="text-align: center"><img src="<?= $this->basePath($cor); ?>"></td>
                  <td style="text-align: center"><?= $ajuda['matricula']; ?></td>
                  <td style="text-align: center"><?= $ajuda['nome_funcionario']; ?></td>
                  <td style="text-align: center"><?= $ajuda['nome_unidade']; ?></td>
                  <td style="text-align: center"><?= $ajuda['nome_area'].'/'.$ajuda['nome_setor']; ?></td>
                  <td style="text-align: center"><?= $ajuda['data_inicio']; ?></td>
                  <td style="text-align: center"><?= $ajuda['data_fim']; ?></td>
                  <td style="text-align: center"><?= $ajuda['hora_inicio'].' - '.$ajuda['hora_fim']; ?></td>
                  
                </tr>
                <?php endforeach; ?>
              </table>
            </div>
            <?php else: ?>
              <div class="alert alert-info">Nenhuma ajuda encontrada!</div>
            <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($ajudas,
                                        'Sliding',
                                        'view/paginator', array('route' => 'ajudaSolicitada')); 
          ?>
        </div>
      </div>

    <script type="text/javascript">
      $(document).ready(function() {
        $("#inicio").mask("99/99/9999");        
        $("#fim").mask("99/99/9999");
        $("#inicio").datepicker();
        $("#fim").datepicker();
      });
    </script>