    <?php echo $this->partial('form/pesquisa', array('form'=> $formPesquisa, 'route'=> '')) ?>

    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('novoAjudaAdmin'); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Nova ajuda</button>

      
    </div>
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de ajudas</h3>
            </div>
            <div class="panel-body">
              <?php if($ajudas->count() > 0): ?>
                <table class="table">
                  <tr>
                    <th style="text-align: center">Status</th>
                    <th style="text-align: center">Empresa</th>
                    <th style="text-align: center">Unidade</th>
                    <th style="text-align: center">Matrícula</th>
                    <th style="text-align: center">Funcionário</th>
                    <th style="text-align: center">Unidade de origem</th>
                    <th style="text-align: center">Área/setor de destino</th>
                    <th style="text-align: center">Início</th>
                    <th style="text-align: center">Término</th>
                    <th style="text-align: center">Horário</th>
                    <th style="text-align: center">Ações</th>
                </tr>
                <?php foreach($ajudas as $ajuda): ?>
                <tr>
                  <?php 
                    $cor = $this->farol($this->converterData($ajuda['data_inicio']), $this->converterData($ajuda['data_fim']));
                  ?>
                  <td style="text-align: center"><img src="<?= $this->basePath($cor); ?>"></td>
                  <td style="text-align: center"><?= $ajuda['nome_empresa']; ?></td>
                  <td style="text-align: center"><?= $ajuda['nome_unidade']; ?></td>
                  <td style="text-align: center"><?= $ajuda['matricula']; ?></td>
                  <td style="text-align: center"><?= $ajuda['nome_funcionario']; ?></td>
                  <td style="text-align: center"><?= $ajuda['nome_unidade']; ?></td>
                  <td style="text-align: center"><?= $ajuda['nome_area'].'/'.$ajuda['nome_setor']; ?></td>
                  <td style="text-align: center"><?= $ajuda['data_inicio']; ?></td>
                  <td style="text-align: center"><?= $ajuda['data_fim']; ?></td>
                  <td style="text-align: center"><?= $ajuda['hora_inicio'].' - '.$ajuda['hora_fim']; ?></td>
                  
                  <td style="text-align: center;">
                    <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" 
                    onclick="location.href='<?= $this->url('alterarAjudaAdmin', array('id' => $ajuda['id'])); ?>'" style="cursor: pointer;">

                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            <?php else: ?>
              <div class="alert alert-info">Nenhuma ajuda encontrada!</div>
            <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($ajudas,
                                        'Sliding',
                                        'view/paginator', array('route' => 'listarAjudaAdmin')); 
          ?>
        </div>
      </div>

    <script type="text/javascript">
      $(document).ready(function() {
        $("#inicio").mask("99/99/9999");
        
        $("#fim").mask("99/99/9999");
      });
    </script>