 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('novoContratacao'); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Nova contratação</button>

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('home'); ?>">Home</a></li>
      <li><a href="<?= $this->url('listarContratacao'); ?>">Contratações</a></li>
      <li class="active">Alterar</li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Alterar contratação (funcionário)</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formFuncionario, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>

    <script type="text/javascript">
      $(document).ready(function() {
        $("#data_inicio").mask("99/99/9999");
        $("#data_nascimento").mask("99/99/9999");
        $("#data_saida").mask("99/99/9999");

        $("#data_inicio").datepicker();
        $("#data_nascimento").datepicker();
        $("#data_saida").datepicker();

        $("#inicio_turno").mask("99:99");
        $("#fim_turno").mask("99:99");
      });
    </script>