    <?php echo $this->partial('form/pesquisa', array('form'=> $formPesquisa, 'route'=> '')) ?>

    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('novoAvaliacoesDesempenho'); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Nova avaliação de desempenho</button>

      <div style="float:left;">
        <span><img src="<?= $this->basePath('img/verde.png'); ?>"> Feedback realizado</span>
        <span style="margin-left:5px;"><img src="<?= $this->basePath('img/cinza.png'); ?>"> Feedback em aberto</span>
        <span style="margin-left:5px;"><img src="<?= $this->basePath('img/amarelo.png'); ?>"> Faltam até 3 dias para feedback vencer</span>
        <span style="margin-left:5px;"><img src="<?= $this->basePath('img/vermelho.png'); ?>"> Feedback vencido</span>
      </div>
    </div>
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de avaliações de desempenho</h3>
            </div>
            <div class="panel-body">
              <?php if($avaliacoes->count() > 0): ?>
                <table class="table">
                  <tr>
                    <th style="text-align: center">Status</th>
                    <th style="text-align: center">Área</th>
                    <th style="text-align: center">Setor</th>
                    <th style="text-align: center">Função</th>
                    <th style="text-align: center">Matrícula</th>
                    <th style="text-align: center">Funcionário</th>
                    <th style="text-align: center">Data da avaliação</th>
                    <th style="text-align: center">Data do próximo feedback</th>
                    <th style="text-align: center">Ações</th>
                </tr>
                <?php foreach($avaliacoes as $avaliacao): ?>
                <tr>
                  <?php 
                    if($avaliacao['feedback_realizado'] == 'S'){
                      //VERDE
                      $cor = 'img/verde.png';
                    }else{
                      $dataAvaliacao = strtotime($this->converterData($avaliacao['data_proximo_feedback']));
                      if($dataAvaliacao < strtotime(date('Y-m-d'))){
                        //vermelho
                        $cor = 'img/vermelho.png';
                      }else{
                        if($dataAvaliacao >= strtotime(date('Y-m-d')) 
                          && $dataAvaliacao <= strtotime(date('Y-m-d', strtotime("+3 days",strtotime(date('Y-m-d')))))){
                          //amarelo
                          $cor = 'img/amarelo.png';
                        }else{
                          //cinza
                          $cor = 'img/cinza.png';
                        }
                      }
                      
                    }
                  ?>
                  <td style="text-align: center"><img src="<?= $this->basePath($cor); ?>"></td>
                  <td style="text-align: center"><?= $avaliacao['nome_area']; ?></td>
                  <td style="text-align: center"><?= $avaliacao['nome_setor']; ?></td>
                  <td style="text-align: center"><?= $avaliacao['nome_funcao']; ?></td>
                  <td style="text-align: center"><?= $avaliacao['matricula']; ?></td>
                  <td style="text-align: center"><?= $avaliacao['nome_funcionario']; ?></td>
                  <td style="text-align: center"><?= $avaliacao['data']; ?></td>
                  <td style="text-align: center"><?= $avaliacao['data_proximo_feedback']; ?></td>
                  <td style="text-align: center;">
                    <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" 
                    onclick="location.href='<?= $this->url('alterarAvaliacoesDesempenho', array('id' => $avaliacao['id'])); ?>'" style="cursor: pointer;">

                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            <?php else: ?>
              <div class="alert alert-info">Nenhuma avaliação de desempenho encontrada!</div>
            <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($avaliacoes,
                                        'Sliding',
                                        'view/paginator', array('route' => 'listarAvaliacoesDesempenho')); 
          ?>
        </div>
      </div>

    <script type="text/javascript">
      $(document).ready(function() {
        $("#inicio").mask("99/99/9999");
        $("#fim").mask("99/99/9999");
        $("#inicio").datepicker();
        $("#fim").datepicker();
      });
    </script>