<?php
  $diasSemana = array('D', 'S', 'T', 'Q', 'Q', 'S', 'S');
  $ultimoDia = date("t", mktime(0,0,0,$escala['mes'],'01',$escala['ano'])); 
?>

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('home'); ?>">Home</a></li>
      <li><a href="<?= $this->url('listarEscalasAdmin'); ?>">Pesquisar escala</a></li>
      <li class="active">Preencher</li>
    </ol>

              <h3 class="panel-title">Preencher escala</h3>
            <?php if(count($escalas) == 0): ?>
              <div class="alert alert-info">NÃO EXISTE FUNCIONÁRIO VINCULADO PARA ESTE GESTOR!</div>
            <?php else: ?>
            <form name="frmEscala" action="" method="POST">
            <table class="table">
                  <tr>
                    <th style="text-align: center;background-color:#333f4f;color:#ffffff;" colspan="<?php echo 4 + $ultimoDia; ?>"><?= $escala['mes'].'/'.$escala['ano'] ?></th>
                </tr>
                <tr>
                    <th style="text-align: center; background-color:#305496; color:#ffffff;" colspan="4"></th>
                <?php 
                  $numeroDia = date('w', strtotime($escala['ano'].'-'.$escala['mes'].'-'.'01'));
                  
                  for ($i=1; $i <= $ultimoDia; $i++) : ?>
                    <th style="text-align: center; background-color: #bfbfbf;"><?= $diasSemana[$numeroDia]; ?></th>
                    <?php
                      if($numeroDia == 6){
                        $numeroDia = 0;
                      }else{
                        $numeroDia++;
                      }
                    ?>    

                <?php endfor; ?>
                </tr>
              <tr>
                  <td style="text-align: center; background-color:#305496; color:#ffffff;">Nome</td>
                  <td style="text-align: center; background-color:#305496; color:#ffffff;">Cargo</td>
                  <td style="text-align: center; background-color:#305496; color:#ffffff;">Horário</td>
                  <td style="text-align: center; background-color:#305496; color:#ffffff;">C.HORÁRIA</td>
                  <?php 
                    for ($i=1; $i <= $ultimoDia; $i++) {
                      echo '<td style="text-align: center; background-color: #bfbfbf;">'.$i.'</td>';
                    }
                  ?>
                </tr>
                <?php foreach ($escalas as $escalaFunc): ?>
                  <tr>
                    <td style="text-align: center"><?= $escalaFunc['nome'] ?></td>
                    <td style="text-align: center"><?= $escalaFunc['nome_funcao'] ?></td>
                    <td style="text-align: center"><?= substr($escalaFunc['inicio_turno'], 0, -3).' - '.substr($escalaFunc['fim_turno'], 0, -3) ?></td>
                    <td style="text-align: center">C.HORÁRIA</td>
                    <?php 
                      foreach ($escalaFunc['dias'] as $dia => $value) {
                        $numeroDia = date('w', strtotime($escala['ano'].'-'.$escala['mes'].'-'.$dia));
                        
                        //ausencia
                        if($value == 'A'){
                          echo '<td style="text-align: center;background-color:#f2dede;"></td>';
                          continue;
                        }

                        //ferias
                        if($value == 'F'){
                          echo '<td style="text-align: center;background-color:#dff0d8;"></td>';
                          continue;
                        }


                        $checked = '';
                        if($value == 'E'){
                          $checked = 'CHECKED';
                        }
                        if($numeroDia == 0 || $numeroDia == 6){
                          echo '<td style="text-align: center; background-color: #bfbfbf;" onclick="check(\'#'.$escalaFunc['id'].'-'.$dia.'\');">
                              <input '.$checked.' type="checkbox" name="'.$escalaFunc['id'].'-'.$dia.'" id="'.$escalaFunc['id'].'-'.$dia.'">
                            </td>';
                        }else{
                         echo '<td style="text-align: center;" onclick="check(\'#'.$escalaFunc['id'].'-'.$dia.'\');">
                              <input '.$checked.' type="checkbox" name="'.$escalaFunc['id'].'-'.$dia.'" id="'.$escalaFunc['id'].'-'.$dia.'">
                            </td>';
                        }
                      }
                    ?>
                  </tr>
                <?php endforeach; ?>
            </table>

            <table style="border:none;">
              <tr style="border:none;">
                <td style="border:none;width:30px;background-color:#dff0d8;"></td>
                <td style="padding: 5px;border:none;"> Férias</td>
                <td style="border:none;width:30px;background-color:#f2dede;"></td>
                <td style="padding: 5px;border:none;margin:3px;"> Ausência</td>
            </table>

              <button type="submit" class="btn btn-success" style="float: right;margin-right: 10px;">
                <img src="<?= $this->basePath('img/salvar.png'); ?>" alt="Salvar">
                Salvar
              </button>

              <button type="button" class="btn btn-warning" style="float: right;margin-right: 10px;" onClick="selecionarTodos();">
                <img src="<?= $this->basePath('img/assigntome.png'); ?>" alt="Salvar">
                Selecionar todos
              </button>

              <button type="button" class="btn btn-danger" style="float: right;margin-right: 10px;" onClick="mensagem('<?= $this->url('replicarEscala', array('mes' => $escala['mes'], 'ano' => $escala['ano'], 'setor' => $escala['setor'], 'unidade' => $escala['unidade'])); ?>', 'Atenção: esta opção irá deletar todos os dados deste mês e replicar os dados do mês anterior, confirma a operação?');">
                <img src="<?= $this->basePath('img/copy.png'); ?>" alt="Salvar">
                Replicar do mês anterior
              </button>

              <button type="button" class="btn btn-default" style="float: right;margin-right: 10px;" onClick="location.href='<?= $this->url('exportarEscalaAdmin', array('escala' => $escala['id'])); ?>';">
                <img src="<?= $this->basePath('img/excel.png'); ?>" alt="Salvar">
                Exportar em excel
              </button>

            </form>

            <div class="container theme-showcase" role="main">
            </div>
            <br>
            <div class="panel panel-default">
              <div class="panel-heading">
                  <h3 class="panel-title">Vincular arquivo</h3>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                      <?php if(!empty($escala['caminho_arquivo'])): ?>
                      <a href="<?= $this->url('download', array('id' => $escala['id'], 'service' => 'Escala', 'campo' => 'caminho_arquivo')); ?>">
                        <button type="button" style="width:100%;" class="btn btn-info">
                            <img src="<?= $this->basePath('img/download32.png'); ?>" style="width:32px;height:32px;">
                            Download do arquivo
                        </button>
                      </a>
                    <?php endif; ?>

                      <?php echo $this->partial('form/generic', array('form'=> $formArquivo, 'route'=> '')) ?>

                </div>
              </div>
            </div>
            <?php endif; ?>
      

<style type="text/css">
table {
    border-collapse: collapse;
}

table, th, td {
    border: 1px solid black;
}
</style>

<script type="text/javascript">
  function selecionarTodos(){
    <?php foreach ($nomesBotao as $nome) : ?>
      $('<?php echo "#".$nome; ?>').attr('checked', 'checked');
    <?php endforeach; ?>
  }
</script>