    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('novoBancoHoras'); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novo banco de horas</button>

      
    </div>
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de banco de horas</h3>
            </div>
            <div class="panel-body">
              <?php if($bancos->count() > 0): ?>
                <table class="table">
                  <tr>
                    <th style="text-align: center">Início</th>
                    <th style="text-align: center">Fim</th>
                    <th style="text-align: center">Arquivo</th>
                    <th style="text-align: center">Ações</th>
                </tr>
                <?php foreach($bancos as $banco): ?>
                <tr>
                  <td style="text-align: center"><?= $this->converterData($banco['inicio']); ?></td>
                  <td style="text-align: center"><?= $this->converterData($banco['fim']); ?></td>
                  <td style="text-align: center"><a href="<?= $this->basePath($banco['caminho']); ?>" download><img src="<?= $this->basePath('img/download.png') ?>"> Download do arquivo</a></td>
                  
                  <td style="text-align: center;">
                    <img src="<?= $this->basePath('img/deletar.png'); ?>" title="Deletar" style="cursor: pointer;" onclick="alerta('<?= $this->url('deletarBancoHoras', array('id' => $banco['id'])); ?>', 'deletar');">

                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            <?php else: ?>
              <div class="alert alert-info">Nenhum banco de horas encontrado!</div>
            <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($bancos,
                                        'Sliding',
                                        'view/paginator', array('route' => 'listarBancoHoras')); 
          ?>
        </div>
      </div>