    <?php echo $this->partial('form/pesquisa', array('form'=> $formPesquisa, 'route'=> '')) ?>

    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
       <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('novoSetor'); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novo setor</button>

      
    </div>
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de setores</h3>
            </div>
            <div class="panel-body">
              <?php if($setores->count() > 0): ?>
                <table class="table">
                  <tr>
                    <th style="text-align: center">Nome da área</th>
                    <th style="text-align: center">Nome do setor</th>
                    <th style="text-align: center">Status</th>
                    <th style="text-align: center">Ações</th>
                </tr>
                <?php foreach($setores as $setor): ?>
                <tr>
                  <td style="text-align: center"><?= $setor['nome_area']; ?></td>
                  <td style="text-align: center"><?= $setor['nome']; ?></td>
                  <td style="text-align: center"><?= $this->status($setor['ativo']); ?></td>
                  <td style="text-align: center;">
                    <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" 
                    onclick="location.href='<?= $this->url('alterarSetor', array('id' => $setor['id'])); ?>'" style="cursor: pointer;">
                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            <?php else: ?>
              <div class="alert alert-info">Nenhum setor encontrado!</div>
            <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($setores,
                                        'Sliding',
                                        'view/paginator', array('route' => 'listarSetor')); 
          ?>
        </div>
      </div>