    <?php echo $this->partial('form/pesquisa', array('form'=> $formPesquisa, 'route'=> '')) ?>

    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">

    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
       <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('novoFuncionario'); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novo funcionário</button>

       <button type="button" class="btn btn-warning" onclick="location.href='<?= $this->url('importarFuncionario'); ?>'" style="float: right;margin-right:5px;">
      <img src="<?php echo $this->basePath('img/assigntome.png') ?>" alt="Importar">
      Importar funcionários</button>

      <button type="button" class="btn btn-danger" onclick="location.href='<?= $this->url('trocarGestor'); ?>'" style="float: right;margin-right:5px;">
      <img src="<?php echo $this->basePath('img/redirecionar.png') ?>" alt="Importar">
      Alterar gestor</button>
    </div>
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de funcionários</h3>
            </div>
            <div class="panel-body">
              <?php if($funcionarios->count() > 0): ?>
                <table class="table">
                  <tr>
                    <th style="text-align: center">Filial</th>
                    <th style="text-align: center">Descrição da unidade</th>
                    <th style="text-align: center">Matrícula</th>
                    <th style="text-align: center">Nome</th>
                    <th style="text-align: center">Data de nascimento</th>
                    <th style="text-align: center">Cargo</th>
                    <th style="text-align: center">C Custo</th>
                    <th style="text-align: center">Desc centro custo</th>
                    <th style="text-align: center">Horário</th>
                    <th style="text-align: center">Status</th>
                    <th style="text-align: center">Ações</th>
                </tr>
                <?php foreach($funcionarios as $funcionario): ?>
                <tr>
                  <td style="text-align: center"><?= $funcionario['id_unidade']; ?></td>
                  <td style="text-align: center"><?= $funcionario['nome_unidade']; ?></td>
                  <td style="text-align: center"><?= $funcionario['matricula']; ?></td>
                  <td style="text-align: center"><?= $funcionario['nome']; ?></td>
                  <td style="text-align: center"><?= $funcionario['data_nascimento']; ?></td>
                  <td style="text-align: center"><?= $funcionario['nome_funcao']; ?></td>
                  <td style="text-align: center"><?= $funcionario['ccusto']; ?></td>
                  <td style="text-align: center"><?= $funcionario['desc_ccusto']; ?></td>
                  <td style="text-align: center"><?= $funcionario['horario']; ?></td>
                  <td style="text-align: center"><?= $this->status($funcionario['ativo']); ?></td>
                  <td style="text-align: center;">
                    <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" 
                    onclick="location.href='<?= $this->url('alterarFuncionario', array('id' => $funcionario['id'])); ?>'" style="cursor: pointer;">
                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            <?php else: ?>
              <div class="alert alert-info">Nenhum funcionário encontrado!</div>
            <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($funcionarios,
                                        'Sliding',
                                        'view/paginator', array('route' => 'listarFuncionario')); 
          ?>
        </div>
      </div>