 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('home'); ?>">Home</a></li>
      <li><a href="<?= $this->url('listarFuncionario'); ?>">Funcionários</a></li>
      <li class="active">Alterar gestor</li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Alterar gestor</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formGestor, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>