    <?php echo $this->partial('form/pesquisa', array('form'=> $formPesquisa, 'route'=> '')) ?>

    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
       <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('novoFeriasAdmin'); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novas férias</button>

      
    </div>
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de férias</h3>
            </div>
            <div class="panel-body">
              <?php if($ferias->count() > 0): ?>
                <table class="table">
                  <tr>
                    <th style="text-align: center">status</th>
                    <th style="text-align: center">Empresa</th>
                    <th style="text-align: center">Unidade</th>
                    <th style="text-align: center">Área</th>
                    <th style="text-align: center">Setor</th>
                    <th style="text-align: center">Função</th>
                    <th style="text-align: center">Funcionário</th>
                    <th style="text-align: center">Início</th>
                    <th style="text-align: center">Fim</th>
                    <th style="text-align: center">Ações</th>
                </tr>
                <?php foreach($ferias as $feria): ?>
                <tr>
                  <?php 
                    $cor = $this->farol($this->converterData($feria['data_inicio']), $this->converterData($feria['data_fim']));
                  ?>
                  <td style="text-align: center"><img src="<?= $this->basePath($cor); ?>"></td>
                  <td style="text-align: center"><?= $feria['nome_empresa']; ?></td>
                  <td style="text-align: center"><?= $feria['nome_unidade']; ?></td>
                  <td style="text-align: center"><?= $feria['nome_area']; ?></td>
                  <td style="text-align: center"><?= $feria['nome_setor']; ?></td>
                  <td style="text-align: center"><?= $feria['nome_funcao']; ?></td>
                  <td style="text-align: center"><?= $feria['nome_funcionario']; ?></td>
                  <td style="text-align: center"><?= $feria['data_inicio']; ?></td>
                  <td style="text-align: center"><?= $feria['data_fim']; ?></td>
                  <td style="text-align: center;">
                    <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" 
                    onclick="location.href='<?= $this->url('alterarFeriasAdmin', array('id' => $feria['id'])); ?>'" style="cursor: pointer;">
                    

                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            <?php else: ?>
              <div class="alert alert-info">Nenhuma férias encontrada!</div>
            <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($ferias,
                                        'Sliding',
                                        'view/paginator', array('route' => 'listarFeriasAdmin')); 
          ?>
        </div>
      </div>

    <script type="text/javascript">
      $(document).ready(function() {
        $("#inicio_inicio").mask("99/99/9999");
        $("#inicio_fim").mask("99/99/9999");
        $("#fim_inicio").mask("99/99/9999");
        $("#fim_fim").mask("99/99/9999");
      });
    </script>