    <?php echo $this->partial('form/pesquisa', array('form'=> $formPesquisa, 'route'=> '')) ?>

    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('novoAusencia'); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Nova ausência</button>

      
    </div>
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de ausências</h3>
            </div>
            <div class="panel-body">
              <?php if($ausencias->count() > 0): ?>
                <table class="table">
                  <tr>
                    <th style="text-align: center">Área</th>
                    <th style="text-align: center">Setor</th>
                    <th style="text-align: center">Função</th>
                    <th style="text-align: center">Matrícula</th>
                    <th style="text-align: center">Funcionário</th>
                    <th style="text-align: center">Data</th>
                    <th style="text-align: center">Ações</th>
                </tr>
                <?php foreach($ausencias as $ausencia): ?>
                <tr>
                  <td style="text-align: center"><?= $ausencia['nome_area']; ?></td>
                  <td style="text-align: center"><?= $ausencia['nome_setor']; ?></td>
                  <td style="text-align: center"><?= $ausencia['nome_funcao']; ?></td>
                  <td style="text-align: center"><?= $ausencia['matricula']; ?></td>
                  <td style="text-align: center"><?= $ausencia['nome_funcionario']; ?></td>
                  <td style="text-align: center"><?= $ausencia['data']; ?></td>
                  <td style="text-align: center;">
                    <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" 
                    onclick="location.href='<?= $this->url('alterarAusencia', array('id' => $ausencia['id'])); ?>'" style="cursor: pointer;">

                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            <?php else: ?>
              <div class="alert alert-info">Nenhuma ausência encontrada!</div>
            <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($ausencias,
                                        'Sliding',
                                        'view/paginator', array('route' => 'listarAusencia')); 
          ?>
        </div>
      </div>

    <script type="text/javascript">
      $(document).ready(function() {
        $("#inicio").mask("99/99/9999");
        $("#fim").mask("99/99/9999");
      });
    </script>