<div class="container theme-showcase" role="main" style="margin-bottom:10px;"> 
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="form-group">
          <form class="form-inline" role="form" method="POST" action="#">
            <!-- EXIBIR CAMPOS DO FORM -->
            <?php $colunas = 0; ?>
            <?php foreach ($form->getElements() as $element): ?>
            <?php if($colunas == 0): ?>
            <div class="row" style="margin-top:20px;">
            <?php endif; ?>

              <div class='col-sm-4'>
                <div class="form-group">

                  <?php if($element->getLabel()) :?>
                    <label for="<?=$element->getName()?>" style="width:139px;"><?=$element->getLabel()?></label>
                  <?php endif;?>
            
                  <?= $this->formElement($element); ?>
                  <?= $this->formElementErrors($element, array('class' => 'alert alert-danger')); ?>

                </div>
              </div>
            <?php 
              if($colunas == 2){
                echo '</div>';
                $colunas = 0;
              }else{
                $colunas++;
              }
            ?>
          <?php endforeach; ?>
            <?php 
              if($colunas != 0){
                echo '</div>';
              }
            ?>
            <div class="row" style="margin-top:20px;">
              
              <button type="submit" name="pesquisar" class="btn btn-info" style="float: right;margin-right: 10px;">
                <img src="<?= $this->basePath('img/pesquisar.png'); ?>" alt="Pesquisar"> Pesquisar
              </button>
              
              <button name="limpar" type="submit" class="btn btn-default" 
                  style="float: right;margin-right: 10px;">
                <img src="<?= $this->basePath('img/limpar.png'); ?>"> Limpar
              </button>

              <?php if(!isset($notExcel)): ?>
                <button type="submit" class="btn btn-success" name="exportar"  style="float: right;margin-right: 10px;">
                <img src="<?= $this->basePath('img/excel.png'); ?>" alt="Exportar">
              <?php endif; ?>
              </button>

            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>