<?php if ($this->pageCount): ?>
<ul class="pagination">
  <li>
    <a href="<?php echo $this->url($this->route, array('page' => $this->previous)); ?>">
      &laquo;
    </a>
  </li>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <li>
      <a href="<?php echo $this->url($this->route, array('page' => $page)); ?>">
          <?php echo $page; ?>
      </a>
    </li>
  <?php else: ?>
    <li class="active">
      <a href="">
        <?php echo $page; ?>
      </a>
    </li>
  <?php endif; ?>
<?php endforeach; ?>

  <li>
    <a href="<?php echo $this->url($this->route, array('page' => $this->next)); ?>">
      &raquo;
    </a>
  </li>
<?php endif; ?>