<?php echo $this->doctype(); ?>
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <?php echo $this->headTitle('Mapa Alliar')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))


                ->prependStylesheet($this->basePath() . '/css/fullcalendar.css')
                ->prependStylesheet($this->basePath() . '/vendor/font-awesome/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/vendor/morrisjs/morris.css')
                ->prependStylesheet($this->basePath() . '/dist/css/sb-admin-2.css')
                ->prependStylesheet($this->basePath() . '/vendor/metisMenu/metisMenu.min.css')
                ->prependStylesheet($this->basePath() . '/vendor/bootstrap/css/bootstrap.css'); ?>


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

                <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/ui.datepicker-pt-BR.js')
            ->prependFile($this->basePath() . '/js/fullcalendar/pt-br.js')
            ->prependFile($this->basePath() . '/js/fullcalendar.js')
            ->prependFile($this->basePath() . '/js/moment.js')
            ->prependFile($this->basePath() . '/js/bootbox.min.js')
            

            ->prependFile($this->basePath() . '/js/jquery.maskedinput.min.js')
            ->prependFile($this->basePath() . '/js/funcoes.js')
            ->prependFile($this->basePath() . '/dist/js/sb-admin-2.js')
            ->prependFile($this->basePath() . '/vendor/morrisjs/morris.min.js')
            ->prependFile($this->basePath() . '/vendor/raphael/raphael.min.js')
            ->prependFile($this->basePath() . '/vendor/metisMenu/metisMenu.min.js')
            ->prependFile($this->basePath() . '/vendor/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/vendor/jquery/jquery.min.js'); 


    $rota = explode("\\", $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch()->getParam('controller'));

    $action = explode("\\", $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch()->getParam('action'));

    $usuario = $this->getHelperPluginManager()->getServiceLocator()->get('session')->read();
?>

    </head>
<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0; background: linear-gradient(154deg, #008fe2 0, #00b29c 100%);">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                        <img src="<?= $this->basePath('img/logo.png'); ?>" style="margin-top:5px;">
                
                            
                <!-- <a class="navbar-brand" href="index.html">SB Admin v2.0</a> -->
            </div>
                <div class="row">
                    <div class="col-sm-10">
                        <div style="margin-left: 248px;margin-bottom:10px;">
                            <h2 style="color:#fff;margin-bottom:0px">MAPA</h2>
                            <span style="color:#fff">METODOLOGIA ADMINISTRAÇÃO DE PESSOAL ALLIAR</span>
                        </div>

                        <div style="float: right;margin-top:-50px;color:#fff;">
                            <img src="<?= $this->basePath('img/usuario.png'); ?>"> 
                                <?= $usuario['nome'] ?>
                        </div>
                    </div>

                    
                </div>
                <!--

                    <span style="color:#fff">
                        </span>
                </div>
            <!-- /.navbar-header -->

            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" style="margin-top:0px;" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a class="<?= $rota[0] == 'Application' ? 'active' : ''; ?>" href="<?= $this->url('home'); ?>"> Home</a>
                        </li>
                        <li>
                            <a href="#" style="background-color:#DEB887;"> Cadastros</a>
                            <ul class="nav nav-second-level">
                                <li class="<?= $rota[2] == 'Empresa' ? 'active' : ''; ?>"><a href="<?= $this->url('listarEmpresa'); ?>">Empresa</a></li>
                                        <li class="<?= $rota[2] == 'Area' ? 'active' : ''; ?>"><a href="<?= $this->url('listarArea'); ?>">Área</a></li>
                                        <li class="<?= $rota[2] == 'Setor' ? 'active' : ''; ?>"><a href="<?= $this->url('listarSetor') ?>">Setor</a></li>
                                        <li class="<?= $rota[2] == 'Funcao' ? 'active' : ''; ?>"><a href="<?= $this->url('listarFuncao'); ?>">Função</a></li>
                                        <li class="<?= $rota[2] == 'Funcionario' ? 'active' : ''; ?>"><a href="<?= $this->url('listarFuncionario'); ?>">Funcionário</a></li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#" style="background-color:#f2dede;"> Mensal</a>
                            <ul class="nav nav-second-level">
                                 <li><a href="<?= $this->url('menuPremissasAdmin'); ?>">Premissas</a></li>
                                        <li><a href="" onclick="alert('A fazer');">Simulador</a></li>
                                        <li class="<?= $rota[2] == 'Ferias' ? 'active' : ''; ?>"><a href="<?= $this->url('listarFeriasAdmin'); ?>">Férias</a></li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#" style="background-color:#d9edf7;"> Semanal</a>
                            <ul class="nav nav-second-level">
                                 <li class="<?= $rota[2] == 'Organizacaoequipes' ? 'active' : ''; ?>"><a href="<?= $this->url('pesquisarEquipesAdmin'); ?>">Organização de equipes</a></li>
                                        <li class="<?= $rota[2] == 'Escala' ? 'active' : ''; ?>"><a href="<?= $this->url('listarEscalasAdmin'); ?>">Escalas</a></li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#" style="background-color:#dff0d8;"> Diário - Admin. pessoal</a>
                            <ul class="nav nav-second-level">
                                  <li class="<?= $rota[2] == 'Acoes' ? 'active' : ''; ?>"><a href="<?= $this->url('listarAcoesDisciplinaresAdmin'); ?>">Ações disciplinares</a></li>
                                        <li class="<?= $rota[2] == 'Desempenho' ? 'active' : ''; ?>"><a href="<?= $this->url('listarAvaliacoesDesempenhoAdmin'); ?>">Feedback</a></li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#" style="background-color:#fcf8e3;"> Diário - Controle de operação</a>
                            <ul class="nav nav-second-level">
                                  <li class="<?= $rota[2] == 'Ausencia' ? 'active' : ''; ?>"><a href="<?= $this->url('listarAusenciaAdmin'); ?>">Controle de ausência</a></li>
                                        <li class="<?= $rota[2] == 'Ajuda' ? 'active' : ''; ?>"><a href="<?= $this->url('listarAjudaAdmin'); ?>">Ajudas</a></li>
                                        <li class="<?= $rota[2] == 'Substituicao' ? 'active' : ''; ?>"><a href="<?= $this->url('listarSubstituicaoAdmin'); ?>">Substituição programada</a></li>
                                        <li class="<?= $rota[2] == 'Banco' ? 'active' : ''; ?>"><a href="<?= $this->url('listarBancoHorasAdmin'); ?>">Banco de horas</a></li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#" style="background-color:#FFE1FF;"> Avaliações de desempenho</a>
                            <ul class="nav nav-second-level">
                                  <li class="<?= $action[0] == 'indexavaliacaoresponder' || $action[0] == 'novoavaliacao' ? 'active' : ''; ?>"><a href="<?= $this->url('listarPeriodo'); ?>">Períodos de avaliação</a></li>
                                        <li class="<?= $action[0] == 'indexavaliacaorespondida' || $action[0] == 'visualizaravaliacao' ? 'active' : ''; ?>"><a href="<?= $this->url('listarAvaliacoesRespondidasAdmin'); ?>">Visualizar avaliações</a></li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a class="<?= $rota[0] == 'Usuario' ? 'active' : ''; ?>" style="background-color:#fcf8e3;" href="<?= $this->url('usuario'); ?>"> Usuários</a>
                        </li>
                        <li>
                            <a href="<?= $this->url('logout'); ?>"> Sair</a>
                        </li>
                       
                       
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper" style="margin-top: 50px;">
            
        <?= $this->flashMessenger()->render('error', array('alert', 'alert-danger')) ?>   

        <?= $this->flashMessenger()->render('warning', array('alert',  'alert-warning')) ?>
        
        <?= $this->flashMessenger()->render('success', array('alert',  'alert-success')) ?>


        <?php echo $this->content; ?>

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->

</body>
</html>