    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-danger">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de avaliações em aberto</h3>
            </div>
            <div class="panel-body">
              <?php if(count($avaliacoes) > 0): ?>
                <table class="table">
                  <tr>
                    <th style="text-align: center">Matrícula</th>
                    <th style="text-align: center">Funcionário</th>
                    <th style="text-align: center">Área</th>
                    <th style="text-align: center">Setor</th>
                    <th style="text-align: center">Início</th>
                    <th style="text-align: center">Fim</th>
                    <th style="text-align: center">Período</th>
                    <th style="text-align: center">Referencia</th>
                    <th style="text-align: center">Ações</th>
                </tr>
                <?php foreach($avaliacoes as $key => $avaliacao): ?>
                  <?php foreach ($avaliacao['funcionarios'] as $funcionario) : ?>
                <tr>
                  <td style="text-align: center"><?= $funcionario['matricula'] ?></td>
                  <td style="text-align: center"><?= $funcionario['nome'] ?></td>
                  <td style="text-align: center"><?= $funcionario['nome_area'] ?></td>
                  <td style="text-align: center"><?= $funcionario['nome_setor'] ?></td>
                  <td style="text-align: center"><?= $this->converterData($avaliacoes[$key]['data_inicio']);  ?></td>
                  <td style="text-align: center"><?= $this->converterData($avaliacoes[$key]['data_fim']); ?></td>
                  <td style="text-align: center">
                    <?= $this->converterData($avaliacoes[$key]['referencia_inicio']).' a '.
                      $this->converterData($avaliacoes[$key]['referencia_fim']);;  ?>
                  </td>
                  <td style="text-align: center"><?= $avaliacoes[$key]['nome_referencia'] ?></td>

                  <td style="text-align: center;">
                    <img src="<?= $this->basePath('img/responder.png'); ?>" title="Editar" 
                    onclick="location.href='<?= $this->url('novoAvaliacao', array('funcionario' => $funcionario['id'], 'referencia' => $avaliacoes[$key]['id'])); ?>'" style="cursor: pointer;">

                  </td>
                </tr>
                  <?php endforeach; ?>
                <?php endforeach; ?>
              </table>
            <?php else: ?>
              <div class="alert alert-info">Nenhuma avaliação em aberto!</div>
            <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

