    <?php echo $this->partial('form/pesquisa', array('form'=> $formPesquisa, 'route'=> '', 'notExcel' => '')) ?>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de avaliações respondidas</h3>
            </div>
            <div class="panel-body">
              <?php if($avaliacoes->count() > 0): ?>
                <table class="table">
                  <tr>
                    <th style="text-align: center">Empresa</th>
                    <th style="text-align: center">Unidade</th>
                    <th style="text-align: center">Matrícula</th>
                    <th style="text-align: center">Funcionário</th>
                    <th style="text-align: center">Área</th>
                    <th style="text-align: center">Setor</th>
                    <th style="text-align: center">Início</th>
                    <th style="text-align: center">Fim</th>
                    <th style="text-align: center">Período</th>
                    <th style="text-align: center">Referencia</th>
                    <th style="text-align: center">Ações</th>
                </tr>
                <?php foreach($avaliacoes as $avaliacao): ?>
                <tr>
                  <td style="text-align: center"><?= $avaliacao['nome_empresa'] ?></td>
                  <td style="text-align: center"><?= $avaliacao['nome_unidade'] ?></td>
                  <td style="text-align: center"><?= $avaliacao['matricula'] ?></td>
                  <td style="text-align: center"><?= $avaliacao['nome_funcionario'] ?></td>
                  <td style="text-align: center"><?= $avaliacao['nome_area'] ?></td>
                  <td style="text-align: center"><?= $avaliacao['nome_setor'] ?></td>
                  <td style="text-align: center"><?= $this->converterData($avaliacao['data_inicio']);  ?></td>
                  <td style="text-align: center"><?= $this->converterData($avaliacao['data_fim']); ?></td>
                  <td style="text-align: center">
                    <?= $this->converterData($avaliacao['referencia_inicio']).' a '.
                      $this->converterData($avaliacao['referencia_fim']);;  ?>
                  </td>
                  <td style="text-align: center"><?= $avaliacao['nome_referencia'] ?></td>

                  <td style="text-align: center;">
                    <img src="<?= $this->basePath('img/visualizar.png'); ?>" title="Visualizar avaliação" 
                    onclick="location.href='<?= $this->url('visualizarAvaliacaoAdmin', array('id' => $avaliacao['id'])); ?>'" style="cursor: pointer;">

                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            <?php else: ?>
              <div class="alert alert-info">Nenhuma avaliação em aberto!</div>
            <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($avaliacoes,
                                        'Sliding',
                                        'view/paginator', array('route' => 'listarAvaliacoesRespondidasAdmin')); 
          ?>
        </div>
      </div>

    <script type="text/javascript">
      $(document).ready(function() {
        $("#inicio").mask("99/99/9999");
        $("#fim").mask("99/99/9999");
      });
    </script>