<?php if($erro): ?>
<div class="container theme-showcase" role="main" style="margin-top:100px;padding: 0px;">
  <div class="alert alert-danger">
    Ocorreu algum erro, por favor tente novamente!
  </div>
</div>
<?php endif; ?>

 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('novoPeriodo'); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novo período de avaliação</button>

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('home'); ?>">Home</a></li>
      <li><a href="<?= $this->url('listarPeriodo'); ?>">Períodos de avaliação</a></li>
      <li class="active">Novo</li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Inserir período de avaliação</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formPilha, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>

    <script type="text/javascript">
      $(document).ready(function() {
        $("#data_inicio").mask("99/99/9999");
        $("#data_fim").mask("99/99/9999");
        $("#referencia_inicio").mask("99/99/9999");
        $("#referencia_fim").mask("99/99/9999");

      });
    </script>
