  <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('home'); ?>">Home</a></li>
      <li><a href="<?= $this->url('listarAvaliacoesResponder'); ?>">Avaliações em aberto</a></li>
      <li class="active">Nova avaliação</li>
    </ol>
  </div>
<div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">

                <div class="panel">
                    <div class="panel-body">
                        <h2 style="" class="title-hero">
                            Avaliação de desempenho - <?= strtoupper($referencia['nome_referencia']); ?> 
                            (<?= $this->converterData($referencia['referencia_inicio']) ?> a <?= $this->converterData($referencia['referencia_fim']) ?>)
                        </h2>                                
                            <h3 style="" class="title-hero">
                                <?= $referencia['nome_setor'] ?>
                            </h3>
                            <h3 style="" class="title-hero">
                                <?= $funcionario['nome'] ?>
                            </h3>
                            <?php echo $this->partial('form/avaliacao', array('form'=> $formAvaliacao, 'nova'=> true)) ?>           
                    </div>
                </div>
        </div>


<script type="text/javascript">  
$('#enviar').click(function() {
    var c = confirm("A avaliação não poderá ser alterada, confirma o envio das informações?");
    return c;
});
</script>