 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('novoEmpresa'); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Nova empresa</button>

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('home'); ?>">Home</a></li>
      <li><a href="<?= $this->url('listarEmpresa'); ?>">Empresas</a></li>
      <li class="active">Alterar</li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Alterar empresa</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formEmpresa, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>

<div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
    <button type="button" class="btn btn-warning" onclick="location.href='<?= $this->url('alterarEmpresa', array('id' => $empresa['id'])); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Nova unidade
    </button>
</div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-warning">
          <div class="panel-heading">
              <h3 class="panel-title">Vincular unidade</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formUnidade, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>


        <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-warning">
            <div class="panel-heading">
              <h3 class="panel-title">Unidades vinculadas</h3>
            </div>
            <div class="panel-body">
                <table class="table">
                  <tr>
                    <th style="text-align: center">Nome da unidade</th>
                    <th style="text-align: center">Responsável</th>
                    <th style="text-align: center">Ações</th>
                </tr>
                <?php foreach($unidades as $unidade): ?>
                <tr>
                  <td style="text-align: center"><?= $unidade['nome']; ?></td>
                  <td style="text-align: center"><?= $unidade['responsavel']; ?></td>
                  <td style="text-align: center;">
                    <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" 
                    onclick="location.href='<?= $this->url('alterarEmpresa', array('id' => $empresa['id'], 'unidade' => $unidade['id'])); ?>'" style="cursor: pointer;">
                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            </div>
          </div>
        </div>
      </div>