<?php if(!$this->params)$this->params = array();?>
<?php $form->prepare(); ?>
<?php $form->setAttribute('action', "#"); ?>

<?= $this->form()->openTag($form); ?>

<h3 style="" class="title-hero">Atendimento técnico</h3>

<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <label><?= $form->get('rotinas')->getLabel(); ?></label>

        </div>
    </div>
</div>
<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <?= $this->formElement($form->get('rotinas')); ?>
            <?= $this->formElementErrors($form->get('rotinas'), array('class' => 'alert alert-danger')); ?>
            
            <?= $this->formElement($form->get('obs_rotinas')); ?>
            <?= $this->formElementErrors($form->get('obs_rotinas'), array('class' => 'alert alert-danger')); ?>
        </div>
    </div>
</div>
<hr>


<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <label><?= $form->get('aprendizado')->getLabel(); ?></label>

        </div>
    </div>
</div>
<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <?= $this->formElement($form->get('aprendizado')); ?>
            <?= $this->formElementErrors($form->get('aprendizado'), array('class' => 'alert alert-danger')); ?>
            
            <?= $this->formElement($form->get('obs_aprendizado')); ?>
            <?= $this->formElementErrors($form->get('obs_aprendizado'), array('class' => 'alert alert-danger')); ?>
        </div>
    </div>
</div>
<hr>


<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <label><?= $form->get('apresentacao')->getLabel(); ?></label>

        </div>
    </div>
</div>
<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <?= $this->formElement($form->get('apresentacao')); ?>
            <?= $this->formElementErrors($form->get('apresentacao'), array('class' => 'alert alert-danger')); ?>
            
            <?= $this->formElement($form->get('obs_apresentacao')); ?>
            <?= $this->formElementErrors($form->get('obs_apresentacao'), array('class' => 'alert alert-danger')); ?>
        </div>
    </div>
</div>
<hr>

<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <label><?= $form->get('organizacao')->getLabel(); ?></label>

        </div>
    </div>
</div>
<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <?= $this->formElement($form->get('organizacao')); ?>
            <?= $this->formElementErrors($form->get('organizacao'), array('class' => 'alert alert-danger')); ?>
            
            <?= $this->formElement($form->get('obs_organizacao')); ?>
            <?= $this->formElementErrors($form->get('obs_organizacao'), array('class' => 'alert alert-danger')); ?>
        </div>
    </div>
</div>
<hr>

<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <label><?= $form->get('interesse')->getLabel(); ?></label>

        </div>
    </div>
</div>
<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <?= $this->formElement($form->get('interesse')); ?>
            <?= $this->formElementErrors($form->get('interesse'), array('class' => 'alert alert-danger')); ?>
            
            <?= $this->formElement($form->get('obs_interesse')); ?>
            <?= $this->formElementErrors($form->get('obs_interesse'), array('class' => 'alert alert-danger')); ?>
        </div>
    </div>
</div>
<hr>


<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <label><?= $form->get('comunicacao')->getLabel(); ?></label>

        </div>
    </div>
</div>
<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <?= $this->formElement($form->get('comunicacao')); ?>
            <?= $this->formElementErrors($form->get('comunicacao'), array('class' => 'alert alert-danger')); ?>
            
            <?= $this->formElement($form->get('obs_comunicacao')); ?>
            <?= $this->formElementErrors($form->get('obs_comunicacao'), array('class' => 'alert alert-danger')); ?>
        </div>
    </div>
</div>
<hr>


<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <label><?= $form->get('adaptacao')->getLabel(); ?></label>

        </div>
    </div>
</div>
<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <?= $this->formElement($form->get('adaptacao')); ?>
            <?= $this->formElementErrors($form->get('adaptacao'), array('class' => 'alert alert-danger')); ?>
            
            <?= $this->formElement($form->get('obs_adaptacao')); ?>
            <?= $this->formElementErrors($form->get('obs_adaptacao'), array('class' => 'alert alert-danger')); ?>
        </div>
    </div>
</div>
<hr>


<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <label><?= $form->get('acatar')->getLabel(); ?></label>

        </div>
    </div>
</div>
<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <?= $this->formElement($form->get('acatar')); ?>
            <?= $this->formElementErrors($form->get('acatar'), array('class' => 'alert alert-danger')); ?>
            
            <?= $this->formElement($form->get('obs_acatar')); ?>
            <?= $this->formElementErrors($form->get('obs_acatar'), array('class' => 'alert alert-danger')); ?>
        </div>
    </div>
</div>
<hr>


<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <label><?= $form->get('iniciativa')->getLabel(); ?></label>

        </div>
    </div>
</div>
<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <?= $this->formElement($form->get('iniciativa')); ?>
            <?= $this->formElementErrors($form->get('iniciativa'), array('class' => 'alert alert-danger')); ?>
            
            <?= $this->formElement($form->get('obs_iniciativa')); ?>
            <?= $this->formElementErrors($form->get('obs_iniciativa'), array('class' => 'alert alert-danger')); ?>
        </div>
    </div>
</div>
<hr>


<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <label><?= $form->get('relacionamento')->getLabel(); ?></label>

        </div>
    </div>
</div>
<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <?= $this->formElement($form->get('relacionamento')); ?>
            <?= $this->formElementErrors($form->get('relacionamento'), array('class' => 'alert alert-danger')); ?>
            
            <?= $this->formElement($form->get('obs_relacionamento')); ?>
            <?= $this->formElementErrors($form->get('obs_relacionamento'), array('class' => 'alert alert-danger')); ?>
        </div>
    </div>
</div>
<hr>


<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <label><?= $form->get('responsabilidade')->getLabel(); ?></label>

        </div>
    </div>
</div>
<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <?= $this->formElement($form->get('responsabilidade')); ?>
            <?= $this->formElementErrors($form->get('responsabilidade'), array('class' => 'alert alert-danger')); ?>
            
            <?= $this->formElement($form->get('obs_responsabilidade')); ?>
            <?= $this->formElementErrors($form->get('obs_responsabilidade'), array('class' => 'alert alert-danger')); ?>
        </div>
    </div>
</div>
<hr>


<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <label><?= $form->get('motivacao')->getLabel(); ?></label>

        </div>
    </div>
</div>
<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <?= $this->formElement($form->get('motivacao')); ?>
            <?= $this->formElementErrors($form->get('motivacao'), array('class' => 'alert alert-danger')); ?>
            
            <?= $this->formElement($form->get('obs_motivacao')); ?>
            <?= $this->formElementErrors($form->get('obs_motivacao'), array('class' => 'alert alert-danger')); ?>
        </div>
    </div>
</div>
<hr>


<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <label><?= $form->get('assiduidade')->getLabel(); ?></label>

        </div>
    </div>
</div>
<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <?= $this->formElement($form->get('assiduidade')); ?>
            <?= $this->formElementErrors($form->get('assiduidade'), array('class' => 'alert alert-danger')); ?>
            
            <?= $this->formElement($form->get('obs_assiduidade')); ?>
            <?= $this->formElementErrors($form->get('obs_assiduidade'), array('class' => 'alert alert-danger')); ?>
        </div>
    </div>
</div>
<hr>


<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <label><?= $form->get('pontualidade')->getLabel(); ?></label>

        </div>
    </div>
</div>
<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <?= $this->formElement($form->get('pontualidade')); ?>
            <?= $this->formElementErrors($form->get('pontualidade'), array('class' => 'alert alert-danger')); ?>
            
            <?= $this->formElement($form->get('obs_pontualidade')); ?>
            <?= $this->formElementErrors($form->get('obs_pontualidade'), array('class' => 'alert alert-danger')); ?>
        </div>
    </div>
</div>
<hr>


<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <label><?= $form->get('cuidado')->getLabel(); ?></label>

        </div>
    </div>
</div>
<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <?= $this->formElement($form->get('cuidado')); ?>
            <?= $this->formElementErrors($form->get('cuidado'), array('class' => 'alert alert-danger')); ?>
            
            <?= $this->formElement($form->get('obs_cuidado')); ?>
            <?= $this->formElementErrors($form->get('obs_cuidado'), array('class' => 'alert alert-danger')); ?>
        </div>
    </div>
</div>
<hr>

<div class="row form-group">
    <div class="col-sm-12">
            <label><?= $form->get('comentarios')->getLabel(); ?></label>
            <?= $this->formElement($form->get('comentarios')); ?>
            <?= $this->formElementErrors($form->get('comentarios'), array('class' => 'alert alert-danger')); ?>
        
    </div>
</div>
<hr>


<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <label><?= $form->get('parecer_coordenador')->getLabel(); ?></label>

        </div>
    </div>
</div>

<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <?= $this->formElement($form->get('parecer_coordenador')); ?>
            <?= $this->formElementErrors($form->get('parecer_coordenador'), array('class' => 'alert alert-danger')); ?>
        </div>
    </div>
</div>
<hr>

<div class="row form-group">
    <div class="col-sm-12">
        <div class="input-group">
            <label><?= $form->get('parecer_rh')->getLabel(); ?></label>
            <?= $this->formElement($form->get('parecer_rh')); ?>
            <?= $this->formElementErrors($form->get('parecer_rh'), array('class' => 'alert alert-danger')); ?>
        </div>
    </div>
</div>
<hr>

<?php if($nova === true): ?>
<div class="row form-group">
    <div class="col-sm-6">
            <button name="salvar" type="submit" style="width:100%;" class="btn btn-success">
                <img src="<?= $this->basePath('img/salvar64.png');?>"> 
                Salvar avaliação
            </button>
    </div>
    <div class="col-sm-6">
            <button type="submit" name="enviar" id="enviar" style="width:100%;" class="btn btn-danger">
                <img src="<?= $this->basePath('img/confirmar.png');?>"> 
                Enviar avaliação
            </button>
    </div>
</div>
<?php else: ?>
    <?php if(!isset($relatorio)): ?>
        <div class="row form-group">
            <div class="col-sm-12">
                    <button type="button" onclick="location.href='<?= $this->url($nova); ?>'" style="width:100%;" class="btn btn-default">
                        <img src="<?= $this->basePath('img/voltar64.png');?>"> 
                        Voltar
                    </button>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
<?= $this->form()->closeTag($form); ?>
