 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('novoAcoesDisciplinares'); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Nova ação disciplinar</button>

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('home'); ?>">Home</a></li>
      <li><a href="<?= $this->url('listarAcoesDisciplinares'); ?>">Ações disciplinares</a></li>
      <li class="active">Novo</li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Inserir ação disciplinar</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formAcao, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>

    <script type="text/javascript">
      $(document).ready(function() {
        $("#data").mask("99/99/9999");
        $("#data").datepicker();
      });
    </script>