<?php echo $this->partial('form/pesquisa', array('form'=> $formPesquisa, 'route'=> '', 'notExcel' => '')) ?>

<div class="container theme-showcase" role="main" style="margin-bottom: 10px;"> 
  <div class="row">
    <div class="col-sm-3">
      <img src="<?= $this->basePath('img/vermelho.png'); ?>"> <b><?= $ausencias->count(); ?></b> ausências no período
    </div>

    <div class="col-sm-3">
      <img src="<?= $this->basePath('img/cinza.png'); ?>"> <b><?= $ferias->count(); ?></b> férias no período
    </div>

    <div class="col-sm-3">
      <img src="<?= $this->basePath('img/amarelo.png'); ?>"> <b><?= $acoes->count(); ?></b> ação disciplinar no período
    </div>

    <div class="col-sm-3">
      <img src="<?= $this->basePath('img/verde.png'); ?>"> <b><?= $ajudas->count() ?></b> ajudas no período
    </div>
  </div>
</div>



    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="col-sm-6">

          </div>

          <div class="col-sm-6">
            <form name="frmRelatorio" action="" method="POST">
            <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Relatório diário</h3>
              </div>
              <div class="panel-body">
                  <div class="form-group">

                    <div class="col-sm-4">

                    </div>
                    <div class="col-sm-4">
                        <?= $this->formElement($formRelatorio->get('data_referencia')); ?>
                    </div>

                    <div class="col-sm-4">
                      <button type="submit" class="btn btn-success" style="float: right;margin-right: 10px;">
                        <img src="<?php echo $this->basePath('img/excel.png') ?>" alt="Salvar">
                        Gerar relatório
                      </button>
                    </div>

              </div>
            </div>
          </div>
        </form>
        </div>
    </div>
    </div>



<div class="container theme-showcase" role="main" style="">  
  <div class="row">
    <div class="col-sm-6">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title">Ausências do mês (De <?= $this->converterData($inicio); ?> até <?= $this->converterData($fim); ?>)</h3>
        </div>
        <div class="panel-body">
          <div class="form-group">
              <div id='ausencias'></div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Funcionários de férias (De <?= $this->converterData($inicio); ?> até <?= $this->converterData($fim); ?>)</h3>
        </div>
        <div class="panel-body">
          <div class="form-group">
              <div id='ferias'></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-sm-6">
      <div class="panel panel-warning">
        <div class="panel-heading">
          <h3 class="panel-title">Ações disciplinares (De <?= $this->converterData($inicio); ?> até <?= $this->converterData($fim); ?>)</h3>
        </div>
        <div class="panel-body">
          <div class="form-group">
              <div id='acoes'></div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title">Ajudas (De <?= $this->converterData($inicio); ?> até <?= $this->converterData($fim); ?>)</h3>
        </div>
        <div class="panel-body">
          <div class="form-group">
              <div id='ajudas'></div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
<script type="text/javascript">
  $(document).ready(function() {
    
    $('#ausencias').fullCalendar({
      header: {
        left: '',
        center: 'title',
        right: 'month,agendaWeek,agendaDay'
      },
      defaultDate: '<?= date("Y-m-d") ?>',
      defaultView: 'month',
      editable: true,
      events: [
        <?php foreach ($ausencias as $ausencia) : ?>
          {
            title: '<?= $ausencia["nome_funcionario"] ?>',
            start: '<?= $ausencia["data"] ?>'
          },
        <?php endforeach; ?>
      ],
      dayClick: function(date, jsEvent, view) {
        eventoCalendario(date.format(), 1, <?= $funcionario['unidade'] ?>);
      }
    });
    $('#ausencias').fullCalendar('gotoDate', '<?= $inicio ?>');

    $('#ferias').fullCalendar({
      header: {
        left: '',
        center: 'title',
        right: 'month,agendaWeek,agendaDay'
      },
      defaultDate: '<?= date("Y-m-d") ?>',
      defaultView: 'month',
      editable: true,
      events: [
        <?php foreach ($ferias as $feria) : ?>
          {
            title: '<?= $feria["nome_funcionario"] ?>',
            start: '<?= $feria["data_inicio"] ?>',
            end:   '<?php echo date("Y-m-d", strtotime("+1 days",strtotime($feria["data_fim"]))); ?>'
          },
        <?php endforeach; ?>
      ],
      dayClick: function(date, jsEvent, view) {
        eventoCalendario(date.format(), 2, <?= $funcionario['unidade'] ?>);
      }
    });
    $('#ferias').fullCalendar('gotoDate', '<?= $inicio ?>');

    $('#acoes').fullCalendar({
      header: {
        left: '',
        center: 'title',
        right: 'month,agendaWeek,agendaDay'
      },
      defaultDate: '<?= date("Y-m-d") ?>',
      defaultView: 'month',
      editable: true,
      events: [
        <?php foreach ($acoes as $acao) : ?>
          {
            title: '<?= $acao["nome_funcionario"] ?>',
            start: '<?= $acao["data"] ?>'
          },
        <?php endforeach; ?>
      ],
      dayClick: function(date, jsEvent, view) {
        eventoCalendario(date.format(), 3, <?= $funcionario['unidade'] ?>);
      }
    });
    $('#acoes').fullCalendar('gotoDate', '<?= $inicio ?>');

    $('#ajudas').fullCalendar({
      header: {
        left: '',
        center: 'title',
        right: 'month,agendaWeek,agendaDay'
      },
      defaultDate: '<?= date("Y-m-d") ?>',
      defaultView: 'month',
      editable: true,
      events: [
        <?php foreach ($ajudas as $ajuda) : ?>
          {
            title: '<?= $ajuda["nome_funcionario"] ?>',
            start: '<?= $ajuda["data_inicio"] ?>',
            end:   '<?php echo date("Y-m-d", strtotime("+1 days",strtotime($ajuda["data_fim"]))); ?>'
          },
        <?php endforeach; ?>
      ],
      dayClick: function(date, jsEvent, view) {
        eventoCalendario(date.format(), 4, <?= $funcionario['unidade'] ?>);
      }
    });
    $('#ajudas').fullCalendar('gotoDate', '<?= $inicio ?>');
  });
</script>

    <script type="text/javascript">
      $(document).ready(function() {
        $("#inicio").mask("99/99/9999");        
        $("#fim").mask("99/99/9999");
        $("#data_referencia").mask("99/99/9999");
        $("#inicio").datepicker();
        $("#fim").datepicker();
        $("#data_referencia").datepicker();
      });
    </script>