<?php echo $this->partial('form/pesquisa', array('form'=> $formPesquisa, 'route'=> '', 'notExcel' => '')) ?>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="col-sm-6">
            <div class="row">
              <div class="col-sm-3">
                <img src="<?= $this->basePath('img/vermelho.png'); ?>"> <b><?= $ausencias->count(); ?></b> ausências no período<br>
                <b><?= $ausenciasAtestado->count() ?></b> ausências com atestado
              </div>

              <div class="col-sm-3">
                <img src="<?= $this->basePath('img/cinza.png'); ?>"> <b><?= $ferias->count(); ?></b> férias no período
              </div>

              <div class="col-sm-3">
                <img src="<?= $this->basePath('img/amarelo.png'); ?>"> <b><?= $acoes->count(); ?></b> ação disciplinar no período
              </div>

              <div class="col-sm-3">
                Ajudas: 
                <img src="<?= $this->basePath('img/verde.png'); ?>" title="Ajudas requisitadas"> 
                <b><?= $ajudasSolicitadas->count() ?></b> 
                
                <img src="<?= $this->basePath('img/azul.png'); ?>" title="Ajudas enviadas"> 
                <b><?= $ajudasRecebidas->count() ?></b>  
                 
              </div>
            </div>
          </div>

          <div class="col-sm-6">
            <form name="frmRelatorio" action="" method="POST">
            <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Relatório diário</h3>
              </div>
              <div class="panel-body">
                  <div class="form-group">

                    <div class="col-sm-4">
                      <div class="form-group">
                        <label for="Início" style="width:139px;">* Início:</label>
                        <?= $this->formElement($formRelatorio->get('inicio_referencia')); ?>
                      </div>

                    </div>
                    <div class="col-sm-4">

                      <div class="form-group">
                        <label for="Fim" style="width:139px;">* Fim:</label>
                        <?= $this->formElement($formRelatorio->get('fim_referencia')); ?>
                      </div>
                    </div>

                    <div class="col-sm-4">
                      <br>
                      <div class="form-group">
                        <button type="submit" class="btn btn-success" style="float: right;margin-right: 10px;">
                          <img src="<?php echo $this->basePath('img/excel.png') ?>" alt="Salvar">
                          Gerar relatório
                        </button>
                      </div>
                    </div>

              </div>
            </div>
          </div>
        </form>
        </div>
    </div>
    </div>



<div class="container theme-showcase" role="main" style="">  
  <div class="row">
    <div class="col-sm-6">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title">Ausências do mês (De <?= $this->converterData($inicio); ?> até <?= $this->converterData($fim); ?>)</h3>
        </div>
        <div class="panel-body">
          <div class="form-group">
              <div id='ausencias'></div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Funcionários de férias (De <?= $this->converterData($inicio); ?> até <?= $this->converterData($fim); ?>)</h3>
        </div>
        <div class="panel-body">
          <div class="form-group">
              <div id='ferias'></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-sm-6">
      <div class="panel panel-warning">
        <div class="panel-heading">
          <h3 class="panel-title">Ações disciplinares (De <?= $this->converterData($inicio); ?> até <?= $this->converterData($fim); ?>)</h3>
        </div>
        <div class="panel-body">
          <div class="form-group">
              <div id='acoes'></div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title">Ajudas (De <?= $this->converterData($inicio); ?> até <?= $this->converterData($fim); ?>)</h3>
        </div>
        <div class="panel-body">
          <div class="form-group">
              <div id='ajudas'></div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
<script type="text/javascript">
  $(document).ready(function() {
    
    $('#ausencias').fullCalendar({
      header: {
        left: '',
        center: 'title',
        right: 'month,agendaWeek,agendaDay'
      },
      dayRender: function (date, cell) {
        <?php foreach ($anotacoesAusencias as $ausencia) : ?>
          if (date.format("YYYY-MM-DD") == "<?= $ausencia['data'] ?>") {
            cell.css("background-color", "#FFDEAD");
          }
        <?php endforeach; ?>
      },
      defaultDate: '<?= date("Y-m-d") ?>',
      defaultView: 'month',
      editable: true,
      events: [
        <?php foreach ($ausencias as $ausencia) : ?>
          {
            title: '<?= $ausencia["nome_funcionario"] ?>',
            start: '<?= $ausencia["data"] ?>',
            end:   '<?php echo date("Y-m-d", strtotime("+1 days",strtotime($ausencia["data_fim"]))); ?>'
          },
        <?php endforeach; ?>
      ],
      dayClick: function(date, jsEvent, view) {
        eventoCalendario(date.format(), 1, <?= $funcionario['unidade'] ?>, this);
      }
    });
    $('#ausencias').fullCalendar('gotoDate', '<?= $inicio ?>');

    $('#ferias').fullCalendar({
      header: {
        left: '',
        center: 'title',
        right: 'month,agendaWeek,agendaDay'
      },
      dayRender: function (date, cell) {
        <?php foreach ($anotacoesFerias as $dia) : ?>
          if (date.format("YYYY-MM-DD") == "<?= $dia['data'] ?>") {
            cell.css("background-color", "#FFDEAD");
          }
        <?php endforeach; ?>
      },
      defaultDate: '<?= date("Y-m-d") ?>',
      defaultView: 'month',
      editable: true,
      events: [
        <?php foreach ($ferias as $feria) : ?>
          {
            title: '<?= $feria["nome_funcionario"] ?>',
            start: '<?= $feria["data_inicio"] ?>',
            end:   '<?php echo date("Y-m-d", strtotime("+1 days",strtotime($feria["data_fim"]))); ?>'
          },
        <?php endforeach; ?>
      ],
      dayClick: function(date, jsEvent, view) {
        eventoCalendario(date.format(), 2, <?= $funcionario['unidade'] ?>, this);
      }
    });
    $('#ferias').fullCalendar('gotoDate', '<?= $inicio ?>');

    $('#acoes').fullCalendar({
      header: {
        left: '',
        center: 'title',
        right: 'month,agendaWeek,agendaDay'
      },
      dayRender: function (date, cell) {
        <?php foreach ($anotacoesAcoes as $dia) : ?>
          if (date.format("YYYY-MM-DD") == "<?= $dia['data'] ?>") {
            cell.css("background-color", "#FFDEAD");
          }
        <?php endforeach; ?>
      },
      defaultDate: '<?= date("Y-m-d") ?>',
      defaultView: 'month',
      editable: true,
      events: [
        <?php foreach ($acoes as $acao) : ?>
          {
            title: '<?= $acao["nome_funcionario"] ?>',
            start: '<?= $acao["data"] ?>'
          },
        <?php endforeach; ?>
      ],
      dayClick: function(date, jsEvent, view) {
        eventoCalendario(date.format(), 3, <?= $funcionario['unidade'] ?>, this);
      }
    });
    $('#acoes').fullCalendar('gotoDate', '<?= $inicio ?>');

    $('#ajudas').fullCalendar({
      header: {
        left: '',
        center: 'title',
        right: 'month,agendaWeek,agendaDay'
      },
      dayRender: function (date, cell) {
        <?php foreach ($anotacoesAjudas as $dia) : ?>
          if (date.format("YYYY-MM-DD") == "<?= $dia['data'] ?>") {
            cell.css("background-color", "#FFDEAD");
          }
        <?php endforeach; ?>
      },
      defaultDate: '<?= date("Y-m-d") ?>',
      defaultView: 'month',
      editable: true,
      events: [
        <?php foreach ($ajudasRecebidas as $ajuda) : ?>
          {
            title: '<?= $ajuda["nome_funcionario"] ?>',
            start: '<?= $ajuda["data_inicio"] ?>',
            end:   '<?php echo date("Y-m-d", strtotime("+1 days",strtotime($ajuda["data_fim"]))); ?>',
            color: '#5cb85c'
          },
        <?php endforeach; ?>
        <?php foreach ($ajudasSolicitadas as $ajuda) : ?>
          {
            title: '<?= $ajuda["nome_funcionario"] ?>',
            start: '<?= $ajuda["data_inicio"] ?>',
            end:   '<?php echo date("Y-m-d", strtotime("+1 days",strtotime($ajuda["data_fim"]))); ?>',
            color: '#31b0d5'
          },
        <?php endforeach; ?>

      ],
      eventRender: function (event, element, view) {
        if (event.color) {
          element.css('background-color', event.color)
        }
      },
      dayClick: function(date, jsEvent, view) {
        eventoCalendario(date.format(), 4, <?= $funcionario['unidade'] ?>, this);
      }
    });
    $('#ajudas').fullCalendar('gotoDate', '<?= $inicio ?>');
  });
</script>

    <script type="text/javascript">
      $(document).ready(function() {
        $("#inicio").mask("99/99/9999");        
        $("#fim").mask("99/99/9999");
        $("#inicio").datepicker();
        $("#fim").datepicker();
        
        $("#inicio_referencia").mask("99/99/9999");
        $("#inicio_referencia").datepicker();

        $("#fim_referencia").mask("99/99/9999");
        $("#fim_referencia").datepicker();
      });
    </script>