    <?php echo $this->partial('form/pesquisa', array('form'=> $formPesquisa, 'route'=> '')) ?>

    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
       <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('novoArea'); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Nova área</button>

      
    </div>
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de áreas</h3>
            </div>
            <div class="panel-body">
              <?php if($areas->count() > 0): ?>
                <table class="table">
                  <tr>
                    <th style="text-align: center">Nome da área</th>
                    <th style="text-align: center">Responsável</th>
                    <th style="text-align: center">Status</th>
                    <th style="text-align: center">Ações</th>
                </tr>
                <?php foreach($areas as $area): ?>
                <tr>
                  <td style="text-align: center"><?= $area['nome']; ?></td>
                  <td style="text-align: center"><?= $area['responsavel']; ?></td>
                  <td style="text-align: center"><?= $this->status($area['ativo']); ?></td>
                  <td style="text-align: center;">
                    <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" 
                    onclick="location.href='<?= $this->url('alterarArea', array('id' => $area['id'])); ?>'" style="cursor: pointer;">
                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            <?php else: ?>
              <div class="alert alert-info">Nenhuma área encontrada!</div>
            <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($areas,
                                        'Sliding',
                                        'view/paginator', array('route' => 'listarArea')); 
          ?>
        </div>
      </div>